import './globals.css';
import Navbar from './components/Navbar/index';
import Footer from './components/Footer/Footer';
import logo from '../public/assets/logo/logo.png';
import React from 'react';


export const metadata = {
  title: 'Nobl Kids',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* <Navbar /> */}
        {children}
        <Footer />
      </body>
    </html>
  )
}
